### ISSUE TITLE
Support custom conversion during binlog synchronization

### ISSUE THREAD

**Issue by ThroughWeb** [AirToSupply/hudi-spark-plus#2]
Hi, Town：
    Does it support data set column clipping when real-time synchronization is performed through binlog，My thoughts are as follows：
    (1) Support user-defined SQL to simply process data sets during synchronization.
    (2) Multi column derived fields are supported for partition column assignment of Hoodie table.

**Comment by AirToSupply** [comment]
I get it! 
I plan to add a user-defined logic before data warehousing, which can support SQL semantics firstly.
